// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0
// source: db.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getContactInfoByEmailORPhone = `-- name: GetContactInfoByEmailORPhone :many
SELECT id, email, phone_number, linked_id, created_at
FROM contact
WHERE
 (email = $1 OR $1 = '') OR (phone_number = $2 OR $2 = '')
`

type GetContactInfoByEmailORPhoneParams struct {
	Email       *string `json:"email"`
	PhoneNumber *string `json:"phone_number"`
}

type GetContactInfoByEmailORPhoneRow struct {
	ID          int32            `json:"id"`
	Email       *string          `json:"email"`
	PhoneNumber *string          `json:"phone_number"`
	LinkedID    *int32           `json:"linked_id"`
	CreatedAt   pgtype.Timestamp `json:"created_at"`
}

func (q *Queries) GetContactInfoByEmailORPhone(ctx context.Context, arg GetContactInfoByEmailORPhoneParams) ([]*GetContactInfoByEmailORPhoneRow, error) {
	rows, err := q.db.Query(ctx, getContactInfoByEmailORPhone, arg.Email, arg.PhoneNumber)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []*GetContactInfoByEmailORPhoneRow
	for rows.Next() {
		var i GetContactInfoByEmailORPhoneRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.PhoneNumber,
			&i.LinkedID,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, &i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertContactInfo = `-- name: InsertContactInfo :one
INSERT INTO contact
    (email, phone_number, linked_id, link_precedence)
VALUES
    ($1, $2, $3, $4)
ON CONFLICT DO NOTHING
RETURNING id
`

type InsertContactInfoParams struct {
	Email          *string            `json:"email"`
	PhoneNumber    *string            `json:"phone_number"`
	LinkedID       *int32             `json:"linked_id"`
	LinkPrecedence LinkPrecedenceEnum `json:"link_precedence"`
}

func (q *Queries) InsertContactInfo(ctx context.Context, arg InsertContactInfoParams) (int32, error) {
	row := q.db.QueryRow(ctx, insertContactInfo,
		arg.Email,
		arg.PhoneNumber,
		arg.LinkedID,
		arg.LinkPrecedence,
	)
	var id int32
	err := row.Scan(&id)
	return id, err
}

const updateContactToSecondary = `-- name: UpdateContactToSecondary :exec
UPDATE contact
SET linked_id = $1, link_precedence = 'secondary'
WHERE
    id = $2
`

type UpdateContactToSecondaryParams struct {
	LinkedID *int32 `json:"linked_id"`
	ID       int32  `json:"id"`
}

func (q *Queries) UpdateContactToSecondary(ctx context.Context, arg UpdateContactToSecondaryParams) error {
	_, err := q.db.Exec(ctx, updateContactToSecondary, arg.LinkedID, arg.ID)
	return err
}
