// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetPrimaryContactInfoByEmailORPhone(ctx context.Context, arg GetPrimaryContactInfoByEmailORPhoneParams) ([]*GetPrimaryContactInfoByEmailORPhoneRow, error)
	GetSecondaryContactInfo(ctx context.Context, linkedID *int32) ([]*GetSecondaryContactInfoRow, error)
	InsertContactInfo(ctx context.Context, arg InsertContactInfoParams) (int32, error)
	UpdateContactToSecondary(ctx context.Context, arg UpdateContactToSecondaryParams) error
}

var _ Querier = (*Queries)(nil)
