// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.26.0

package db

import (
	"context"
)

type Querier interface {
	GetContactInfoByEmailORPhone(ctx context.Context, arg GetContactInfoByEmailORPhoneParams) ([]*GetContactInfoByEmailORPhoneRow, error)
	InsertContactInfo(ctx context.Context, arg InsertContactInfoParams) error
	UpdateContactToSecondary(ctx context.Context, arg UpdateContactToSecondaryParams) error
}

var _ Querier = (*Queries)(nil)
